# Generated by Django 5.2 on 2025-04-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_verified_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
