# Generated by Django 5.2 on 2025-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='chips',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cube',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='decks',
            field=models.JSONField(blank=True, default=dict, help_text='Example: {"deck1": ["card1", "card2"]}', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_users',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='objects_json',
            field=models.JSONField(blank=True, default=dict, help_text='Example: {"photo": "url", "copies": 1}', null=True),
        ),
    ]
