# Generated by Django 5.2.1 on 2025-05-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_game_chips_alter_game_cube_alter_game_decks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
