# Generated by Django 5.2.1 on 2025-05-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('map', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('chips', models.JSONField(blank=True, default=dict, null=True)),
                ('cube', models.JSONField(blank=True, default=dict, null=True)),
                ('decks', models.JSONField(blank=True, default=dict, help_text='Example: {"deck1": ["card1", "card2"]}', null=True)),
                ('objects_json', models.JSONField(blank=True, default=dict, help_text='Example: {"photo": "url", "copies": 1}', null=True)),
                ('rules', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
