# Generated by Django 5.2.1 on 2025-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
