# Generated by Django 5.2.1 on 2025-05-10 02:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_game_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('map', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('chips', models.JSONField(blank=True, default=dict, null=True)),
                ('cube', models.JSONField(blank=True, default=dict, null=True)),
                ('decks', models.JSONField(blank=True, default=dict, help_text='Example: {"deck1": ["card1", "card2"]}', null=True)),
                ('objects_json', models.JSONField(blank=True, default=dict, help_text='Example: {"photo": "url", "copies": 1}', null=True)),
                ('rules', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
