# Generated by Django 5.2.1 on 2025-05-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_room_game_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rules',
            field=models.URLField(null=True),
        ),
    ]
