# Generated by Django 5.2.1 on 2025-05-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_game_rules_alter_room_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.FileField(blank=True, null=True, upload_to='rules/'),
        ),
    ]
